# PyInstaller spec for Ecoscribe.exe (onedir). Build with: python tools/build.py
import os
from pathlib import Path

from PyInstaller.utils.hooks import collect_data_files, collect_dynamic_libs

APP = Path(SPECPATH).parents[1]  # packaging/windows -> the repo
SITE = Path(os.environ.get("ECOSCRIBE_SITE", ""))
KEEP = [l.strip() for l in (Path(SPECPATH) / "cuda_dlls.txt").read_text().splitlines()
        if l.strip() and not l.startswith("#")] if (Path(SPECPATH) / "cuda_dlls.txt").exists() else None

binaries = collect_dynamic_libs("ctranslate2")
for pkg in sorted((SITE / "nvidia").glob("*/bin")):
    for dll in pkg.glob("*.dll"):
        if KEEP is None or dll.name in KEEP:
            binaries.append((str(dll), f"nvidia/{pkg.parent.name}/bin"))

datas = collect_data_files("faster_whisper") + [(str(APP / "ecoscribe" / "web"), "ecoscribe/web")] \
    if (APP / "ecoscribe" / "web").exists() else collect_data_files("faster_whisper")
datas += collect_data_files("tzdata")  # zoneinfo reads the zone files from the tzdata package
icon = Path(SPECPATH) / "ecoscribe.ico"

a = Analysis(
    [str(APP / "packaging" / "entry.py")],  # shared with the Mac build
    pathex=[str(APP)],
    binaries=binaries,
    datas=datas,
    hiddenimports=["tzdata", "dateutil.rrule", "dateutil.tz",  # calendar names (t0u.35): Windows has no tz database
                   "pystray._win32", "comtypes.stream", "win32timezone", "webview.platforms.edgechromium", "pyaudiowpatch",
                   # screen names (t0u.27): UI Automation wrappers, generated by comtypes on the build PC
                   "comtypes.client", "comtypes.gen.UIAutomationClient",
                   "comtypes.gen._944DE083_8FB8_45CF_BCB7_C477ACB2F897_0_1_0", "comtypes.gen.stdole"],
    excludes=["torch", "tensorflow", "matplotlib", "pandas", "scipy", "IPython", "whisper_key",
              "sherpa_onnx", "pytest", "edge_tts", "PyInstaller"],
    noarchive=False,
)
pyz = PYZ(a.pure)
exe = EXE(pyz, a.scripts, [], exclude_binaries=True, name="Ecoscribe", console=False,
          icon=str(icon) if icon.exists() else None, version=None)
coll = COLLECT(exe, a.binaries, a.datas, name="Ecoscribe")
